
infra: store
	./manager bag tiddlyweb < /dev/null
	./manager from_svn tiddlyweb http://svn.tiddlywiki.org/Trunk/verticals/tiddlywebclient/plugins/TiddlyWebAdaptorPlugin.js http://svn.tiddlywiki.org/Trunk/verticals/tiddlywebclient/plugins/TiddlyWebAutoSavePlugin.js http://svn.tiddlywiki.org/Trunk/verticals/tiddlywebclient/plugins/TiddlyWebSpowtDefaulterPlugin.js

store:
	mkdir -p store/bags
	mkdir store/recipes
	mkdir store/users
